#Configuration file for TekkitRestrict
#Author: DreadEnd
#Email: dreadslicer@gmail.com
#BukkitDev: http://dev.bukkit.org/server-mods/tekkit-restrict/

#################################################
######### Anti-Hack Configuration ######### 
# Block hackers from screwing your server up!

## Move Speed Max is the speed in Blocks/second
## (~3 seconds) Move Speed Tolerance is based off the number of "Moves" a player does.

## Fly hack Tolerance is based off the number of "Moves" a player does (1~5 per second).

## Forcefield Tolerance is based off the number of times a player hits a mob or player.

####Default hack names
##	"fly", "forcefield", "speed"

##############################

HackSpeedEnabled: true
HackMoveSpeedMax: 2.5
HackMoveSpeedTolerance: 30

HackFlyEnabled: true
HackFlyTolerance: 60
HackFlyMinHeight: 3

HackForcefieldEnabled: true
HackForcefieldTolerance: 15
HackForcefieldAngle: 40


HackBan: []
HackKick: ["fly","forcefield","speed"]
HackBroadcasts: ["fly","forcefield","speed"]
HackBroadcastString: "{PLAYER} tried to {TYPE}-hack!"


####Dupes####
Dupes:
    PreventAlchemyBagDupe: true
    PreventRMFurnaceDupe: true
    PreventTransmuteDupe: true
    PreventTankCartDupe: true
    PreventTankCartGlitch: true
    PreventTeleportDupe: true
    PreventPedestalEmcGen: true
    BroadcastString: "{PLAYER} tried to dupe using {TYPE}!"
    Broadcast: ["rmfurnace", "alc"]
    Kick: []
#####        "RMFurnace", "alc", "transmute", "tankcart"







##############################
##############################
##############################
